blank_issues_enabled: true
contact_links:
  - name: â“ Questions
    url: https://discord.gg/3XGEYY9
    about: Ask your question on the deCONZ community Discord
  - name: ğŸ—‚ Wiki
    url: https://github.com/deconz-community/node-red-contrib-deconz/wiki
    about: Go straight to the wiki
