blank_issues_enabled: true
contact_links:
  - name: â“ Questions
    url: https://discord.gg/3XGEYY9
    about: Ask your question on the deCONZ community Discord
  - name: ğŸ—‚ Documentation
    url: https://deconz-community.github.io/node-red-contrib-deconz/
    about: Go straight to the documentation
